sudo: required
dist: trusty

language: node_js
node_js: 10

os:
  - linux
  - osx

install:
  - npm i -g lix
  - lix download

script:
  - lix run travix interp
  - lix run travix neko
  - lix run travix python
  - lix run travix node
  - lix run travix java
  - lix run travix cpp
  - lix run travix cs
  - lix run travix php
  - lix run travix php7
  - lix run travix lua
