sudo: required
dist: trusty

language: node_js
node_js: 10

os:
  - linux

install:
  - sudo apt-get install -y imagemagick graphicsmagick libvips-tools
  - npm i -g lix
  - lix download

script:
  - lix run travix interp
  - lix run travix neko
  - lix run travix python
  - lix run travix node
  - lix run travix php7

cache:
  directories:
    - $HOME/haxe