name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y imagemagick graphicsmagick libvips-tools
      - run: yarn
      - run: yarn test -D cli
      - run: yarn test:php